import { html } from "lit-element";

export const config = {
    mapboxLightStyle: "https://api.maptiler.com/maps/openstreetmap/style.json?key=",
    heatmapLayers: {
        SALES_MARKET: {
            name: "sales-market",
            id: "sales-market-heatmap-id",
            promoteId: "id",
            source: "sales-market-heatmap-source",
            sourceLayer: "vpgmLayer",
            header: "Sales Market Information",
            minZoom: 1,
            maxZoom: 3,
            vectorTileUrl: "vpgms",
            tableType: "vpgms",
        },
        DMA: {
            name: "dma",
            id: "dma-heatmap-id",
            promoteId: "id",
            source: "dma-heatmap-source",
            sourceLayer: "dmaLayer",
            header: "DMA Information",
            minZoom: 3,
            maxZoom: 5,
            vectorTileUrl: "dmas",
            tableType: "dmas",
            parentLayerIds: [
                "sales-market-heatmap-id",
            ],
        },
        COUNTY: {
            name: "county",
            id: "county-heatmap-id",
            promoteId: "id",
            source: "county-heatmap-source",
            sourceLayer: "countyLayer",
            header: "County Information",
            minZoom: 5,
            maxZoom: 9,
            vectorTileUrl: "counties",
            tableType: "counties",
            parentLayerIds: [
                "dma-heatmap-id",
                "sales-market-heatmap-id",
            ],
        },
        ZIP: {
            name: "zip",
            id: "zipcode-heatmap-id",
            promoteId: "id",
            source: "zipcode-heatmap-source",
            sourceLayer: "zipLayer",
            header: "ZIP Code Information",
            minZoom: 9,
            maxZoom: 14,
            vectorTileUrl: "zips",
            tableType: "zips",
            parentLayerIds: [
                "county-heatmap-id",
                "dma-heatmap-id",
                "sales-market-heatmap-id",
            ],
        },
        CENSUS_BLOCK: {
            name: "census-block",
            id: "census-block-heatmap-id",
            promoteId: "id",
            source: "census-block-heatmap-source",
            sourceLayer: "censusBlockLayer",
            header: "Census Block Information",
            minZoom: 14,
            maxZoom: 20,
            vectorTileUrl: "censusBlocks",
            tableType: "censusblocks",
        },
    },
    boundaryLayers: {
        SALES_MARKET_BOUNDARY_DEFAULT: { // by default we load this layer always on the map
            name: "sales-market-default-boundary",
            id: "sales-market-default-boundary",
            source: "sales-market-default-boundary-source",
        },
        SALES_MARKET_BOUNDARY: { //used for zoom to specifiuc salesMarket when table row is clicked
            name: "sales-market-boundary",
            id: "sales-market-boundary",
            source: "sales-market-boundary-source",
        },
        ZIP_BOUNDARY: {
            name: "zip-boundary",
            id: "zip-boundary",
            source: "zip-boundary-source",
        },
        COUNTY_BOUNDARY: {
            name: "county-boundary",
            id: "county-boundary",
            source: "county-boundary-source",
        },
        DMA_BOUNDARY: {
            name: "dma-boundary",
            id: "dma-boundary",
            source: "dma-boundary-source",
        },
        CENSUS_BLOCK_BOUNDARY: {
            name: "census-block-boundary",
            id: "census-block-boundary",
            source: "census-block-boundary-source",
        },
        DROPDOWN_BOUNDARY: {
            name: "dropdown-boundary",
            id: "dropdown-boundary",
            source: "dropdown-boundary-source",
        },
    },
    pointsLayers: {
        ATTR_POINTS: {            
            promoteId: "location_id",
            id: "attr-storepoint-layer-id",
            name: "AT&T Retail Store",
            source: "attr-storepoint-source",
            //visibility: "none",
            visible: false, // new property to replace visibility
            minZoom: 2,
            checked: false,
            imgUrl: "assets/images/Ellipse-Outline.png",
            svgIcon: html`<ellipse-outline-icon color='#0ABFFF'></ellipse-outline-icon>`,
            color: "#0ABFFF",
            vectorTileUrl: "stores",
            updateSourceData: true,
            minShapeSize: 0.1,
            maxShapeSize: 0.9,
            denominatorValue: 24,
            isAddressLayer: false,
        },
        AR_POINTS: {
            promoteId: "location_id",
            id: "ar-storepoint-layer-id",
            name: "Authorized Reseller Store",
            source: "ar-storepoint-source",
            //visibility: "none",
            visible: false, // new property to replace visibility
            minZoom: 2,
            imgUrl: "assets/images/Ellipse-Outline.png",
            svgIcon: html`<ellipse-outline-icon color='#004B66'></ellipse-outline-icon>`,
            color: "#004B66",
            checked: false,
            vectorTileUrl: "stores",
            updateSourceData: true,
            minShapeSize: 0.1,
            maxShapeSize: 0.9,
            denominatorValue: 24,
            isAddressLayer: false,
        },
        ACC_POINTS: {
            promoteId: "acc_mstr_prpty_id",
            id: "acc-point-layer-id",
            name: "ACC Properties",
            source: "acc-point-source",
            //visibility: "none",
            visible: true, // new property to replace visibility
            minZoom: 2,
            checked: true,
            imgUrl: "assets/images/Rectangle.png",
            svgIcon: html`<rectangle-icon width="8" height="8" color='#8e5723'></rectangle-icon>`,
            color: "#8e5723",
            vectorTileUrl: "accs",
            updateSourceData: true,
            minShapeSize: 0.1,
            maxShapeSize: 0.9,
            denominatorValue: 24,
            isAddressLayer: false,
        },
        PSA_POINTS: {
            promoteId: "ZIP_CO_PSA",
            sourceLayer: "psaLayer",
            id: "psa-point-layer-id",
            name: "PSA Locations",
            source: "psa-point-source",
            sourceLayer: "psaLayer",
            //visibility: "visible",
            visible: true, // new property to replace visibility
            minZoom: 8,
            maxZoom: 15,
            imgUrl: "assets/images/Ellipse.png",
            svgIcon: html`<ellipse-icon width="8" height="8" color="#00cc00"></ellipse-icon>`,
            color: {
                WIRELESS_SCORE_1: "#e6b800",
                WIRELESS_SCORE_2: "#ffff00",
                WIRELESS_SCORE_3: "#00cc00",
                WIRELESS_SCORE_4: "#008000",
                WIRELESS_SCORE_5: "#003300",
            },
            checked: true,
            minShapeSize: 0.1,
            maxShapeSize: 0.9,
            denominatorValue: 36,
            isAddressLayer: false,
        },
        FUTURE_PSA_POINTS: {
            promoteId: "zip_co_psa",
            id: "future-psa-point-layer-id",
            name: "Future PSA Locations",
            source: "future-psa-point-source",
            //visibility: "visible",
            visible: true, // new property to replace visibility
            minZoom: 3,
            svgIcon: html`<triangle-icon color="#00cc00"></triangle-icon>`,
            maxZoom: 15,
            imgUrl: "assets/images/Triangle.png",
            color: {
                WIRELESS_SCORE_1: "#e6b800",
                WIRELESS_SCORE_2: "#ffff00",
                WIRELESS_SCORE_3: "#00cc00",
                WIRELESS_SCORE_4: "#008000",
                WIRELESS_SCORE_5: "#003300",
            },
            checked: true,
            vectorTileUrl: "futurepsas",
            updateSourceData: true,
            minShapeSize: 0.1,
            maxShapeSize: 0.9,
            denominatorValue: 12,
            isAddressLayer: false,
        },
        TOP_25_PSA_POINTS: {
            promoteId: "zip_co_psa",
            id: "top-25-psa-point-layer-id",
            name: "Market Top 25 PSAs",
            source: "top-25-psa-point-source",
            visibility: "visible",
            visible: true, // new property to replace visibility
            minZoom: 3,
            svgIcon: html`<ellipse-icon width="12" height="12" color="#00cc00"></ellipse-icon>`,
            maxZoom: 15,
            imgUrl: "assets/images/Ellipse.png",
            color: {
                WIRELESS_SCORE_1: "#e6b800",
                WIRELESS_SCORE_2: "#ffff00",
                WIRELESS_SCORE_3: "#00cc00",
                WIRELESS_SCORE_4: "#008000",
                WIRELESS_SCORE_5: "#003300",
            },
            checked: true,
            vectorTileUrl: "top25psas",
            updateSourceData: true,
            minShapeSize: 0.1,
            maxShapeSize: 0.9,
            denominatorValue: 12,
            isAddressLayer: false,
        },
        TOP_25_MDU_POINTS: {
            promoteId: "zip_co_psa",
            id: "top-25-mdu-point-layer-id",
            name: "Market Top 25 MDUs",
            source: "top-25-mdu-point-source",
            //visibility: "visible",
            visible: true, // new property to replace visibility
            minZoom: 3,
            maxZoom: 15,
            imgUrl: "assets/images/Rectangle.png",
            svgIcon: html`<rectangle-icon width="12" height="12" color="#00cc00"></rectangle-icon>`,
            color: {
                WIRELESS_SCORE_1: "#e6b800",
                WIRELESS_SCORE_2: "#ffff00",
                WIRELESS_SCORE_3: "#00cc00",
                WIRELESS_SCORE_4: "#008000",
                WIRELESS_SCORE_5: "#003300",
            },
            checked: true,
            vectorTileUrl: "top25mdus",
            updateSourceData: true,
            minShapeSize: 0.1,
            maxShapeSize: 0.9,
            denominatorValue: 12,
            isAddressLayer: false,
        },
        FIBER_CUSTOMER_AND_WIRELESS_CUSTOMER: {
            promoteId: "addr_id",
            id: "fiberCustomerandWirelessCustomerLayer-id",
            name: "Fiber Customer and Wireless Customer",
            source: "fiberCustomerandWirelessCustomerLayer-source",
            sourceLayer: "customerCategoryId1AddressLayer",
            //visibility: "visible",
            visible: true, // new property to replace visibility
            minZoom: 15,
            imgUrl: "assets/images/Ellipse.png",
            svgIcon: html`<ellipse-icon width="8" height="8" color="#00FF00""></ellipse-icon>`,
            color: "#00FF00",
            checked: true,
            minShapeSize: 0.1,
            maxShapeSize: 0.9,
            denominatorValue: 48,
            isAddressLayer: true,
            customerCategoryId: 1,
        },
        FIBER_CUSTOMER_AND_WIRELESS_CROSS_SELL_OPPORTUNITY: {
            promoteId: "addr_id",
            id: "fiberCustomerandWirelessCrossSellOpportunityLayer-id",
            name: "Fiber Customer and Wireless Cross-Sell Opportunity",
            source: "fiberCustomerandWirelessCrossSellOpportunityLayer-source",
            sourceLayer: "customerCategoryId2AddressLayer",
            //visibility: "visible",
            visible: true, // new property to replace visibility
            minZoom: 15,
            imgUrl: "assets/images/Ellipse.png",
            svgIcon: html`<ellipse-icon width="8" height="8" color="#0000FF"></ellipse-icon>`,
            color: "#0000FF",
            checked: true,
            minShapeSize: 0.1,
            maxShapeSize: 0.9,
            denominatorValue: 48,
            isAddressLayer: true,
            customerCategoryId: 2,
        },
        COPPER_UPGRADE_AND_WIRELSS_CUSTOMER: {
            promoteId: "addr_id",
            id: "copperUpgradeandWirelessCustomerLayer-id",
            name: "Copper Upgrade and Wireless Customer",
            source: "copperUpgradeandWirelessCustomerLayer-source",
            sourceLayer: "customerCategoryId3AddressLayer",
            //visibility: "visible",
            visible: true, // new property to replace visibility
            minZoom: 15,
            imgUrl: "assets/images/Ellipse.png",
            svgIcon: html`<ellipse-icon width="8" height="8" color="#B87333"></ellipse-icon>`,
            color: "#B87333",
            checked: true,
            minShapeSize: 0.1,
            maxShapeSize: 0.9,
            denominatorValue: 48,
            isAddressLayer: true,
            customerCategoryId: 3,
        },
        COPPER_UPGRADE_AND_WIRELSS_CROSS_SELL_OPPORTUNITY: {
            promoteId: "addr_id",
            id: "copperUpgradeandWirelessCrossSellOpportunityLayer-id",
            name: "Copper Upgrade and Wireless Cross-Sell Opportunity",
            source: "copperUpgradeandWirelessCrossSellOpportunityLayer-source",
            sourceLayer: "customerCategoryId4AddressLayer",
            //visibility: "visible",
            visible: true, // new property to replace visibility
            minZoom: 15,
            imgUrl: "assets/images/Ellipse.png",
            svgIcon: html`<ellipse-icon width="8" height="8" color="#A020F0"></ellipse-icon>`,
            color: "#A020F0",
            checked: true,
            minShapeSize: 0.1,
            maxShapeSize: 0.9,
            denominatorValue: 48,
            isAddressLayer: true,
            customerCategoryId: 4,
        },
        WIRELESS_CUSTOMER_AND_FIBER_CROSS_SELL_OPPORTUNITY: {
            promoteId: "addr_id",
            id: "wirelessCustomerandFiberCrossSellOpportunityLayer-id",
            name: "Wireless Customer and Fiber Cross-Sell Opportunity",
            source: "wirelessCustomerandFiberCrossSellOpportunityLayer-source",
            sourceLayer: "customerCategoryId5AddressLayer",
            //visibility: "visible",
            visible: true, // new property to replace visibility
            minZoom: 15,
            imgUrl: "assets/images/Ellipse.png",
            svgIcon: html`<ellipse-icon width="8" height="8" color="#FFA500"></ellipse-icon>`,
            color: "#FFA500",
            checked: true,
            minShapeSize: 0.1,
            maxShapeSize: 0.9,
            denominatorValue: 48,
            isAddressLayer: true,
            customerCategoryId: 5,
        },
        OPPORTUNITY_FOR_FIBER_AND_WIRELESS: {
            promoteId: "addr_id",
            id: "opportunityforFiberandWirelessLayer-id",
            name: "Opportunity for Fiber and Wireless",
            source: "opportunityforFiberandWirelessLayer-source",
            sourceLayer: "customerCategoryId6AddressLayer",
            //visibility: "visible",
            visible: true, // new property to replace visibility
            minZoom: 15,
            imgUrl: "assets/images/Ellipse.png",
            svgIcon: html`<ellipse-icon width="8" height="8" color="#FF0000"></ellipse-icon>`,
            color: "#FF0000",
            checked: true,
            minShapeSize: 0.1,
            maxShapeSize: 0.9,
            denominatorValue: 48,
            isAddressLayer: true,
            customerCategoryId: 6,
        },
        MDU_ALL_ATT_FIBER_CUSTOMERS: {
            promoteId: "addr_id",
            id: "mdu-all-att-fiber-customer-layer-id",
            name: "MDU All AT&T Fiber Customers",
            source: "mdu-all-att-fiber-customer-source",
            sourceLayer: "customerCategoryId7AddressLayer",
            //visibility: "visible",
            visible: true, // new property to replace visibility
            minZoom: 15,
            imgUrl: "assets/images/Rectangle-ACC.png",
            svgIcon: html`<rectangle-icon width="8" height="8" color='#00cc00'></rectangle-icon>`,
            color: "#00cc00",
            checked: true,
            minShapeSize: 0.1,
            maxShapeSize: 0.9,
            denominatorValue: 48,
            isAddressLayer: true,
            customerCategoryId: 7,
        },
        MDU_WITH_ATT_FIBER_PROSPECTS: {
            promoteId: "addr_id",
            id: "mdu-with-att-fiber-prospect-layer-id",
            name: "MDU with AT&T Fiber Prospects",
            source: "mdu-with-att-fiber-prospect-source",
            sourceLayer: "customerCategoryId8AddressLayer",
            //visibility: "visible",
            visible: true, // new property to replace visibility
            minZoom: 15,
            imgUrl: "assets/images/Rectangle-ACC.png",
            svgIcon: html`<rectangle-icon width="8" height="8" color='#236B8E'></rectangle-icon>`,
            color: "#236B8E",
            checked: true,
            minShapeSize: 0.1,
            maxShapeSize: 0.9,
            denominatorValue: 48,
            isAddressLayer: true,
            customerCategoryId: 8,
        },
    },
};
