const bcls = require('./bcls');
const byoc = require('./byoc');
const globalBusiness = require('./globalBusiness');
const midmarket = require('./midmarket');
const nationalLUs = require('./nationalLUs');
const nbwc = require('./nbwc');
const omni = require('./omni');
const englite = require('./englite');
module.exports = { bcls, byoc, globalBusiness, midmarket, nationalLUs, nbwc, omni, englite };